---
dependency:
  name: galaxy

driver:
  name: docker

platforms:
  - name: instance
    image: ${MOLECULE_DISTRO:-debian:stretch}
    privileged: true

provisioner:
  name: ansible

verifier:
  name: ansible
